### ISSUE TITLE
Inconsistent behavior regarding cycles

### ISSUE THREAD

**Issue by papb** [ehmicky/error-serializer#1]
Hello! First of all, nice work on all these error-related projects!

This is mainly a question (which will probably result in a request for improving the readme). I was reading the readme and saw this:

> ## JSON safety
> 
> Error plain objects are always [safe to serialize with JSON](https://github.com/ehmicky/safe-json-value).
> 
> ```js
> const error = new Error('example')
> error.cycle = error
>
> // Cycles make `JSON.serialize()` throw, so they are removed
> console.log(serialize(error).cycle) // {}
> ```

After reading the readme of the linked project, [safe-json-value](https://github.com/ehmicky/safe-json-value), I thought `serialize(error).cycle` would be `undefined`, not `{}`. I even thought this was a typo in the readme of this project, but executed it just in case and was surprised that it did result in `{}`. What is the reason for this apparent inconsistency?

**Comment by ehmicky** [comment]
Hi @papb!

Thanks a lot for the kind word :)

This is intentional. The reason is: `errorSerializer. serialize()` first converts the error to a plain object before passing it to `safe-json-value`. However, error static properties are not converted to plain objects. So `safe-json-value` cannot figure out that `error` (now converted to a plain object) is the same as `error.cycle` (not a plain object).

That being said, I agree this is rather surprising when you compare both projects. Replacing circular values with empty objects is probably fine, but `undefined` would be better. The good news is: I am planning to make `error-serializer` deep by default, which should take care of the above problem. I'll update this issue once this is done.

Thanks for pointing this out!

**Comment by ehmicky** [comment]
This should be fixed in [`3.0.0`](https://github.com/ehmicky/error-serializer/releases/tag/3.0.0). Cycles are now removed instead of being set to an empty object.

**Comment by papb** [comment]
Nice work!

**Comment by ehmicky** [comment]
Thanks for pointing this out @papb, I just fixed it.

@all-contributors Please add @papb for bug report and doc.
